changed the build_all script to create the configure file with autoconf
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@1272 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -66,6 +66,10 @@ cd ${SRC}/${APP}
 echo 'workinkg directory: '
 pwd
 echo '+----------------------------------------------------------------------------+'
+echo '| autoconf                                                                   |'
+echo autoconf || (echo "autoconf failed for" $APP ; read)
+autoconf || (echo "autoconf failed for" $APP ; read)
+echo '+----------------------------------------------------------------------------+'
 echo '| configure                                                                  |'
 echo ./configure || (echo "Configure failed for" $APP ; read)
 ./configure || (echo "Configure failed for" $APP ; read)
diff --git a/build_bundle b/build_bundle
--- a/build_bundle
+++ b/build_bundle
@@ -74,9 +74,11 @@ then
 	OUTFILE="2dx_MAC_OS_X_"$SW_VERSION"_"$DATE".pkg"
 	PACKAGE_PATH="installation/packages/"
 	echo "Writing the package "$OUTFILE" to: " $PACKAGE_PATH
-	/Developer/usr/bin/packagemaker -d installation/mac_osx_installer/installer_template.pmdoc -o $PACKAGE_PATH$OUTFILE 
-	#/Developer/usr/bin/packagemaker -d installation/mac_osx_installer/installer_template_test.pmdoc -o $PACKAGE_PATH$OUTFILE 
-
+	#/Developer/usr/bin/packagemaker -d installation/mac_osx_installer/installer_template.pmdoc -o $PACKAGE_PATH$OUTFILE 
+	installation/mac_osx_installer/installer_nightly_build.sh $BUILD_DIR  $PACKAGE_PATH$OUTFILE || (echo "Could not package MAC OS X installer  $PACKAGE_PATH$OUTFILE"; exit 8)
+	if [ $? -gt 0 ]; then
+		exit 8;
+	fi
 fi
 echo '|                                                                            |'
 echo '*============================================================================*'
