Bug in ML-2D and debugging
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@3265 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -111,7 +111,7 @@ cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || 
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make                                                                       |'
-make -j1 || { echo "Build failed for $APP"; exit 6; }
+make VERBOSE=1 -j1 || { echo "Build failed for $APP"; exit 6; }
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make install                                                               |'
