changed the build_all script to build an apple bundle or just regularly build
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@845 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -22,6 +22,12 @@ then
        	PREFIX=~/2dx	
 fi
 
+if [ $# -eq 2 ];
+then
+	APPLE_BUNDLE=$2
+else
+	APPLE_BUNDLE=OFF
+fi
 
 
 # And create build dirs here
@@ -159,7 +165,7 @@ pwd
 echo '+----------------------------------------------------------------------------+'
 echo '| configure                                                                  |'
 echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} . || (echo "Configure failed for" $APP ; read)
-cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} . || (echo "Configure failed for" $APP ; read)
+cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} . || (echo "Configure failed for" $APP ; read)
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make                                                                       |'
