added nightly build script
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@772 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -25,7 +25,7 @@ fi
 
 
 # And create build dirs here
-BUILD=$PREFIX/build
+BUILD=$PREFIX
 SRC=$(pwd)
 BUILD_LIST="
 lib/src/conf 
@@ -126,8 +126,8 @@ do
           echo ''
           echo '+----------------------------------------------------------------------------+'
           echo '| configure                                                                  |'
-          echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ${*} ${SRC}/${TARGET} || (echo "Configure failed for $APP"; read)
-          cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ${*} ${SRC}/${TARGET} || (echo "Configure failed for $APP"; read)
+          echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_MODULE_PATH=${PREFIX}/cmake ${*} ${SRC}/${TARGET} || (echo "Configure failed for $APP"; read)
+          cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_MODULE_PATH=${PREFIX}/cmake ${*} ${SRC}/${TARGET} || (echo "Configure failed for $APP"; read)
           echo ''
           echo '+----------------------------------------------------------------------------+'
           echo '| make                                                                       |'
