sbgrid compile error fixed
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@2133 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -115,7 +115,7 @@ cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || 
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make install                                                               |'
-make -j1 install || { echo "Install failed for $APP"; exit 7; }
+make VERBOSE=1 -j1 install || { echo "Install failed for $APP"; exit 7; }
 echo '*============================================================================*'
 echo ''
 echo ''
