added a build_clean for the nightly_build
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@1279 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_clean b/build_clean
--- a/build_clean
+++ b/build_clean
@@ -75,6 +75,11 @@ echo ./configure || (echo "Configure failed for" $APP ; read)
 ./configure || (echo "Configure failed for" $APP ; read)
 echo ''
 echo '+----------------------------------------------------------------------------+'
+echo '| make clean                                                                 |'
+make VERBOSE=1 -j1 clean || (echo "Clean failed for $APP"; read)
+echo ''
+echo ''
+echo '+----------------------------------------------------------------------------+'
 echo '| make                                                                       |'
 make VERBOSE=1 -j1 || (echo "Build failed for $APP"; read)
 #echo ''
