mrc libs are rebuilt if any of the sources are newer
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@2119 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -111,11 +111,11 @@ cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || 
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make                                                                       |'
-make VERBOSE=1 -j1 || { echo "Build failed for $APP"; exit 6; }
+make -j1 || { echo "Build failed for $APP"; exit 6; }
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make install                                                               |'
-make VERBOSE=1 -j1 install || { echo "Install failed for $APP"; exit 7; }
+make -j1 install || { echo "Install failed for $APP"; exit 7; }
 echo '*============================================================================*'
 echo ''
 echo ''
