fixing bundle for mac os x in the nightly build
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@1436 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -106,8 +106,8 @@ echo 'workinkg directory: '
 pwd
 echo '+----------------------------------------------------------------------------+'
 echo '| configure                                                                  |'
-echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ${SRC} || { echo "Configure failed for" $APP ; exit 5; }  
-cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ${SRC} || { echo "Configure failed for" $APP ; exit 5; }
+echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || { echo "Configure failed for" $APP ; exit 5; }  
+cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || { echo "Configure failed for" $APP ; exit 5; }
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make                                                                       |'
