mrc programs are now also compiled in the build_all script
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@472 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -49,6 +49,36 @@ echo ''
 echo ''
 
 ################################################################################
+# Fortran
+################################################################################
+APP=kernel/mrc
+echo '*============================================================================*'
+echo '| ' ${APP}
+echo '+----------------------------------------------------------------------------+'
+echo '| prepare                                                                    |'
+cd ${SRC}/${APP}
+echo 'workinkg directory: '
+pwd
+echo '+----------------------------------------------------------------------------+'
+echo '| configure                                                                  |'
+echo ./configure || (echo "Configure failed for" $APP ; read)
+./configure || (echo "Configure failed for" $APP ; read)
+echo ''
+echo '+----------------------------------------------------------------------------+'
+echo '| make                                                                       |'
+make VERBOSE=1 -j1 || (echo "Build failed for $APP"; read)
+#echo ''
+#echo '+----------------------------------------------------------------------------+'
+#echo '| make install                                                               |'
+#make VERBOSE=1 -j1 install || (echo "Install failed for $APP"; read)
+echo '*============================================================================*'
+echo ''
+echo ''
+echo ''
+echo ''
+
+
+################################################################################
 # CMake Tools
 ################################################################################
 
