the build_all script executes make install directly, so that the mrc libs are not generated twice (during compilation and installation)
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@2128 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -108,10 +108,10 @@ echo '+-------------------------------------------------------------------------
 echo '| configure                                                                  |'
 echo cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || { echo "Configure failed for" $APP ; exit 5; }  
 cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DAPPLE_BUNDLE=${APPLE_BUNDLE} ${SRC} || { echo "Configure failed for" $APP ; exit 5; }
-echo ''
-echo '+----------------------------------------------------------------------------+'
-echo '| make                                                                       |'
-make -j1 || { echo "Build failed for $APP"; exit 6; }
+#echo ''
+#echo '+----------------------------------------------------------------------------+'
+#echo '| make                                                                       |'
+#make -j1 || { echo "Build failed for $APP"; exit 6; }
 echo ''
 echo '+----------------------------------------------------------------------------+'
 echo '| make install                                                               |'
