upload script called from nightly script appropriate
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@866 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_scripts/nightly_build b/build_scripts/nightly_build
--- a/build_scripts/nightly_build
+++ b/build_scripts/nightly_build
@@ -26,8 +26,11 @@ if [ $? -gt 0 ]; then
 	exit 2;
 fi
 
-SCRIPT_DIR=${SOURCE_DIR}/build_scripts
-
+SCRIPT_DIR=$(pwd)/build_scripts
+if [ ! -d $SCRIPT_DIR ]; then
+	echo "Could not find $SCRIPT_DIR"
+       exit 9;	
+fi
 echo '|                                                                            |'
 echo '*============================================================================*'
 echo ''
