APPLE_BUNDLE set when calling build_all from nightly_build now (inculdes QT Frameworks)
git-svn-id: svn+ssh://svncina.ethz.ch/repos/2dx/trunk@876 cb738334-da44-0410-bf9e-9ace271e2f5b

diff --git a/build_scripts/nightly_build b/build_scripts/nightly_build
--- a/build_scripts/nightly_build
+++ b/build_scripts/nightly_build
@@ -68,8 +68,8 @@ echo '| Calling ./build_all                                                     
 echo '*============================================================================*'
 echo '|                                                                            |'
 
-echo ./build_all $BUILD_DIR || (echo "Could not build the bundle"; exit 4)
-./build_all $BUILD_DIR || (echo "Could not build the bundle"; exit 4)
+echo ./build_all $BUILD_DIR ON || (echo "Could not build the bundle"; exit 4)
+./build_all $BUILD_DIR ON || (echo "Could not build the bundle"; exit 4)
 if [ $? -gt 0 ]; then
 	exit 4;
 fi
